import 'package:flutter/material.dart';
import 'package:flutter_fortune_wheel/flutter_fortune_wheel.dart';

Map<String, List<Map<String, dynamic>>> wheelOptions = {
  'Yes/No':[
    {'label': 'Yes', 'color': Colors.red.shade100},
    {'label': 'No', 'color': Colors.green.shade100},
  ],
  'Food':[
    {'label': 'Pizza', 'color': Colors.tealAccent.shade200},
    {'label': 'Sandwiches', 'color': Colors.lightGreen.shade200},
    {'label': 'Pancake', 'color': Colors.redAccent.shade200},
    {'label': 'Taco', 'color': Colors.lightBlue.shade200},
    {'label': 'Vada Pav', 'color': Colors.purpleAccent.shade200},
    {'label': 'Burrito', 'color': Colors.deepOrange.shade200},
  ],
  'Date ideas':[
    {'label': 'Outdoor Picnic', 'color': Colors.lightBlue},
    {'label': 'Sunset Boat Ride', 'color': Colors.redAccent.shade100},
    {'label': 'Rooftop Dinner', 'color': Colors.tealAccent},
    {'label': 'Game Night', 'color': Colors.deepPurple.shade200},
    {'label': 'Nature Walk', 'color': Colors.greenAccent},
    {'label': 'Picnic in the Park', 'color': Colors.blueGrey.shade100},
    {'label': 'Beach Day', 'color': Colors.amber},
    {'label': 'Spa Day', 'color': Colors.indigo.shade200},
    {'label': 'Hiking Adventure', 'color': Colors.lime},
    {'label': 'Theater', 'color': Colors.blue.shade100},
    {'label': 'Breakfast in Bed', 'color': Colors.teal},
    {'label': 'Restaurant', 'color': Colors.pink.shade200},
  ],
  'Dice 10':[
    {'label': '1', 'color': Colors.pink},
    {'label': '2', 'color': Colors.pink.shade100},
    {'label': '3', 'color': Colors.pink.shade200},
    {'label': '4', 'color': Colors.pink},
    {'label': '5', 'color': Colors.pink.shade100},
    {'label': '6', 'color': Colors.pink.shade200},
    {'label': '7', 'color': Colors.pink},
    {'label': '8', 'color': Colors.pink.shade100},
    {'label': '9', 'color': Colors.pink.shade200},
    {'label': '10', 'color': Colors.pink.shade100},
  ],
  'Movies Night': [
    {'label': 'Horror', 'color': Colors.red.shade800},
    {'label': 'Fantasy', 'color': Colors.purple.shade300},
    {'label': 'Comedy', 'color': Colors.yellow.shade400},
    {'label': 'Reality show', 'color': Colors.orange.shade200},
    {'label': 'Action', 'color': Colors.red.shade200},
    {'label': 'Adventure', 'color': Colors.yellow.shade200},
    {'label': 'Drama', 'color': Colors.teal.shade200},
    {'label': 'Detective', 'color': Colors.cyan.shade200},
    {'label': 'Western', 'color': Colors.indigo.shade200},
    {'label': 'Art-house', 'color': Colors.brown.shade200},
    {'label': 'Family', 'color': Colors.amber.shade200},
    {'label': 'Criminal', 'color': Colors.lime.shade200},
    {'label': 'Thriller', 'color': Colors.deepOrange.shade200},
    {'label': 'Sci-fi', 'color': Colors.pink.shade200},
    {'label': 'Historical', 'color': Colors.purpleAccent.shade200},
    {'label': 'Romantic', 'color': Colors.blueGrey.shade200},
  ],
  'Months': [
    {'label': 'January', 'color': Colors.blue.shade100},
    {'label': 'February', 'color': Colors.green.shade200},
    {'label': 'March', 'color': Colors.purple.shade200},
    {'label': 'April', 'color': Colors.red.shade200},
    {'label': 'May', 'color': Colors.yellow.shade200},
    {'label': 'June', 'color': Colors.teal.shade200},
    {'label': 'July', 'color': Colors.cyan.shade200},
    {'label': 'August', 'color': Colors.indigo.shade200},
    {'label': 'September', 'color': Colors.brown.shade200},
    {'label': 'October', 'color': Colors.amber.shade200},
    {'label': 'November', 'color': Colors.lime.shade200},
    {'label': 'December', 'color': Colors.orange.shade200},
  ],
  'Weekdays': [
    {'label': 'Monday', 'color': Colors.yellow.shade100},
    {'label': 'Tuesday', 'color': Colors.green.shade100},
    {'label': 'Wednesday', 'color': Colors.teal.shade200},
    {'label': 'Thursday', 'color': Colors.amber.shade200},
    {'label': 'Friday', 'color': Colors.blue.shade100},
    {'label': 'Saturday', 'color': Colors.purple.shade200},
    {'label': 'Sunday', 'color': Colors.blue.shade100},
  ],
  'Rainbow colors': [
    {'label': 'Red', 'color': Colors.red},
    {'label': 'Orange', 'color': Colors.orange},
    {'label': 'Yellow', 'color': Colors.yellow},
    {'label': 'Green', 'color': Colors.green},
    {'label': 'Blue', 'color': Colors.blue},
    {'label': 'Indigo', 'color': Colors.indigo},
    {'label': 'Violet', 'color': Colors.purpleAccent},
  ],
  'Create new wheel': [
    {'label': 'Yes', 'color': Colors.red.shade100},
    {'label': 'No', 'color': Colors.green.shade100},
  ],
};